### ISSUE TITLE
IS_CM_SENSOR_RAW8

### ISSUE THREAD

**Issue by tayfun91** [samhitech/microEye#4]
hello deaar,
i get this error.

python version 3.9

C:\Users\Copil\Desktop\microEye-main\examples>python control_module.py
Traceback (most recent call last):
  File "C:\Users\Copil\Desktop\microEye-main\examples\control_module.py", line 1, in <module>
    from microEye.hardware import control_module
  File "C:\Users\Copil\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\microEye\hardware\__init__.py", line 1, in <module>
    from .acquisition_module import acquisition_module
  File "C:\Users\Copil\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\microEye\hardware\acquisition_module.py", line 17, in <module>
    from .CameraListWidget import CameraListWidget
  File "C:\Users\Copil\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\microEye\hardware\CameraListWidget.py", line 10, in <module>
    from .ueye_camera import IDS_Camera
  File "C:\Users\Copil\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\microEye\hardware\ueye_camera.py", line 10, in <module>
    formats_ = {ueye.IS_CM_SENSOR_RAW8: 8,
AttributeError: 'NoneType' object has no attribute 'IS_CM_SENSOR_RAW8'

**Comment by samhitech** [comment]
Hello, I am unsure which version of _microeye_ you are using, but I have fixed this issue in the most recent commit. If the _pyueye_ package and the _IDS SDK_ were not installed this issue arises. Now you can use the hardware part without necessarily needing _IDS_-related software being installed. You might get a similar issue though when it comes to missing _Thorlabs_ drivers for their cameras (_Thorcam_) as it tries to import the _uc480_64.dll_ library from its directory in program files.

**Comment by tayfun91** [comment]
thank u.
this error fixed but i have new error :)
my microEye version 0.3.1


C:\Users\Copil\Desktop\microEye-main\examples>python control_module.py
Traceback (most recent call last):
  File "C:\Users\Copil\Desktop\microEye-main\examples\control_module.py", line 1, in <module>
    from microEye.hardware import control_module
  File "C:\Users\Copil\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\microEye\hardware\__init__.py", line 1, in <module>
    from .acquisition_module import acquisition_module
  File "C:\Users\Copil\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\microEye\hardware\acquisition_module.py", line 18, in <module>
    from ..pyscripting import *
  File "C:\Users\Copil\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\microEye\pyscripting.py", line 2, in <module>
    from pyqode.python.widgets import PyCodeEdit
  File "C:\Users\Copil\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pyqode\python\widgets\__init__.py", line 8, in <module>
    from .code_edit import PyCodeEditBase, PyCodeEdit
  File "C:\Users\Copil\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pyqode\python\widgets\code_edit.py", line 7, in <module>
    from pyqode.python.backend import server
  File "C:\Users\Copil\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pyqode\python\backend\__init__.py", line 7, in <module>
    from .workers import calltips
  File "C:\Users\Copil\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pyqode\python\backend\workers.py", line 182, in <module>
    messages.ReturnWithArgsInsideGenerator,
AttributeError: module 'pyflakes.messages' has no attribute 'ReturnWithArgsInsideGenerator'

**Comment by samhitech** [comment]
Hi, one of the dependencies _pycode.python_ has a problem with the updated package _pyflakes_ which comes with your specific Python version. For _pyflakes_ >= 2.5.0 the attribute '_ReturnWithArgsInsideGenerator_' has been dropped thus a fast fix would be to install _pyflakes_==2.4.0.
`pip install pyflakes==2.4.0`
If you're using Conda then there is a fix to the _pycode.python_ found here [Fix for _pyflakes_ 2.5 #42](https://github.com/pyQode/pyqode.python/pull/42)

I will be closing this issue as it is related to a dependency and Python version mismatch. The _microEye_ is tested with Python >= 3.9.7 yet you might need to install _pyflakes_==2.4.0 for later versions.
